// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    // apiKey: 'AIzaSyCSK0uz9wqngLIJ1yxCrOIQBxQCl7mpy1I',
    // appId: '1:978935243928:web:b290a9804febecac3f1ced',
    // messagingSenderId: '978935243928',
    // projectId: 'automatizacion-ug',
    // authDomain: 'automatizacion-ug.firebaseapp.com',
    // databaseURL: 'https://automatizacion-ug-default-rtdb.firebaseio.com',
    // storageBucket: 'automatizacion-ug.appspot.com',
    // measurementId: 'G-FM3MZM3GXN',
    
    apiKey: "AIzaSyCSK0uz9wqngLIJ1yxCrOIQBxQCl7mpy1I",
    authDomain: "automatizacion-ug.firebaseapp.com",
    databaseURL: "https://automatizacion-ug-default-rtdb.firebaseio.com",
    projectId: "automatizacion-ug",
    storageBucket: "automatizacion-ug.appspot.com",
    messagingSenderId: "978935243928",
    appId: "1:978935243928:web:eb07977329c4a9a83f1ced",
    measurementId: "G-05XSHCHB52"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0lJ_mVKrI3oqDqoJexKzPswQGwkwqBWY',
    appId: '1:978935243928:android:d4a16285c345527c3f1ced',
    messagingSenderId: '978935243928',
    projectId: 'automatizacion-ug',
    databaseURL: 'https://automatizacion-ug-default-rtdb.firebaseio.com',
    storageBucket: 'automatizacion-ug.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNa24S0SgxN3f8Xej2oJ-pdc_nXsmaGHs',
    appId: '1:978935243928:ios:f5a1175ed1bb6d463f1ced',
    messagingSenderId: '978935243928',
    projectId: 'automatizacion-ug',
    databaseURL: 'https://automatizacion-ug-default-rtdb.firebaseio.com',
    storageBucket: 'automatizacion-ug.appspot.com',
    iosClientId: '978935243928-9s4e86lce9qcc9monijif27t5ci70aeq.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashboardTesis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNa24S0SgxN3f8Xej2oJ-pdc_nXsmaGHs',
    appId: '1:978935243928:ios:f9874603661ae8d03f1ced',
    messagingSenderId: '978935243928',
    projectId: 'automatizacion-ug',
    databaseURL: 'https://automatizacion-ug-default-rtdb.firebaseio.com',
    storageBucket: 'automatizacion-ug.appspot.com',
    iosClientId: '978935243928-vss43v5t0olv10g5to1j37aau8v85q2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashboardTesis.RunnerTests',
  );
}
